name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Generated Docs
      run: npm run docs

    - name: Build
      run: |
        npm run build
        cp --force LICENSE.txt system/.
        cp --force README.md system/.
        SYSTEM_VERSION=$(grep -oP '(?<="version": ")[^"]+' system/system.json | tr -d '\n')
        perl -pi -E "s|latest/download/fallout\\.zip|download/release-$SYSTEM_VERSION/fallout.zip|" system/system.json
        echo "systemVersion=$SYSTEM_VERSION" >> $GITHUB_ENV

    - run: cd system && zip -r ../fallout.zip ./*

    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        artifacts: './system/system.json, ./fallout.zip'
        draft: false
        makeLatest: false
        name: release-${{ env.systemVersion }}
        prerelease: true
        tag: release-${{ env.systemVersion }}
        token: ${{ secrets.GITHUB_TOKEN }}
